# Generated by Django 3.0.8 on 2021-01-05 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('d_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
                ('d_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('m_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=20)),
                ('m_amount', models.DecimalField(decimal_places=1, max_digits=8)),
                ('m_price', models.DecimalField(decimal_places=1, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('s_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('s_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('p_price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p_inventory', models.DecimalField(decimal_places=1, max_digits=8)),
                ('m_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('o_amount', models.DecimalField(decimal_places=1, max_digits=8)),
                ('o_price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('o_data', models.DateTimeField(default=datetime.datetime(2021, 1, 5, 13, 3, 18, 9927, tzinfo=utc))),
                ('d_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Dealer')),
                ('p_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
