# Generated by Django 3.0.8 on 2021-01-05 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 13, 5, 7, 556534, tzinfo=utc)),
        ),
    ]
