# Generated by Django 3.0.8 on 2021-01-05 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210105_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 13, 51, 18, 207168, tzinfo=utc)),
        ),
    ]
