# Generated by Django 3.0.8 on 2021-01-05 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210105_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='m_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 14, 14, 24, 12706)),
        ),
    ]
